
#ifndef binary_limine_hdd_bin_data
U8 binary_limine_hdd_bin_data[0];
#endif

#define LIMINE_CFG_BUF_SIZE		8192

Bool LimineBootFilesFind(U8 drv_let)
{
	CDirEntry	 de;
	CDrive		*drive = Letter2Drive(drv_let, FALSE);
	I64			 boot_clus;

	if (!drive || drive->fs_type != FSt_FAT32)
		return FALSE;

	if (!FAT32FileFind(drive, drive->root_clus, "Boot", &de, FUF_JUST_DIRS))
		return FALSE;

	boot_clus = de.clus;

	return FAT32FileFind(drive, boot_clus, "Limine-BIOS.SYS", &de, FUF_JUST_FILES) &&
			FAT32FileFind(drive, boot_clus, "ZealBooter.ELF", &de, FUF_JUST_FILES) &&
			FAT32FileFind(drive, boot_clus, "Kernel.ZXE", &de, FUF_JUST_FILES);
}

Bool LimineCFGMake(U8 drv_let)
{
	U8		 cfg_drv_let = drv_let, entry_drv_let;
	U8		*filename_cfg = MStrPrint("%C:/Boot/Limine.CONF", cfg_drv_let);
	CDrive	*drive;
	I64		 i, cfg_len, entry_len;
	U8		*cfg = MAlloc(LIMINE_CFG_BUF_SIZE), *entry, *st;

	"\nGenerating Limine.CONF ...\n";

	cfg[0] = 0;
	CatPrint(cfg,
			"timeout: 2\n"
			"interface_resolution: 640x480\n\n");

	"Searching drives for Limine bootloader files ...\n";
	for (i = 0, drive = blkdev.drvs; i < DRIVES_NUM; i++, drive++)
	{
		if (drive->drive_signature == DRIVE_SIGNATURE_VAL && drive->fs_type == FSt_FAT32 && DriveIsWritable(drive->drv_let))
		{
			entry_drv_let = Drive2Letter(drive);
			if (LimineBootFilesFind(entry_drv_let))
			{
				entry = MStrPrint("/ZealOS %C:/\n"
					"protocol: limine\n"
					"resolution: 640x480\n"
					"path: boot(%d):/Boot/ZealBooter.ELF\n"
					"module_path: boot(%d):/Boot/Kernel.ZXE\n"
					"\n", entry_drv_let, drive->prt_num + 1, drive->prt_num + 1);
				cfg_len		= StrLen(cfg);
				entry_len	= StrLen(entry);
				if (cfg_len + entry_len < LIMINE_CFG_BUF_SIZE)
				{
					CatPrint(cfg, "%s", entry);
					"%C:/ drive added as a Limine.CONF menu entry.\n", entry_drv_let;
				}
				else
					"%C:/ skipped; Limine.CONF buffer full.\n", entry_drv_let;
				Free(entry);
			}
			else
				"%C:/ drive is missing Limine bootloader files.\n", entry_drv_let;
		}
	}
	cfg_len = StrLen(cfg);
	if (!FileWrite(filename_cfg, cfg, cfg_len))
	{
		PrintErr("Failed to write %s.\n", filename_cfg);
		Free(cfg);
		Free(filename_cfg);

		return FALSE;
	}

	"/Boot/Limine.CONF generated.\n";

	"Copying Limine.CONF to all other drives ...\n";
	for (i = 0, drive = blkdev.drvs; i < DRIVES_NUM; i++, drive++)
	{
		if (drive->drive_signature == DRIVE_SIGNATURE_VAL && drive->fs_type == FSt_FAT32 && DriveIsWritable(drive->drv_let))
		{
			entry_drv_let = Drive2Letter(drive);
			if (entry_drv_let != cfg_drv_let && LimineBootFilesFind(entry_drv_let))
			{
				st = MStrPrint("%C:/Boot/Limine.CONF", entry_drv_let);
				if (FileWrite(st, cfg, cfg_len))
					"%C:/ Limine.CONF copied.\n", entry_drv_let;
				else
					PrintErr("Failed to write %s.\n", st);
				Free(st);
			}
		}
	}
	Free(cfg);
	Free(filename_cfg);

	return TRUE;
}

Bool LimineMHDIns(U8 drv_let)
{
	U8	*limine			= binary_limine_hdd_bin_data;
	U16  limine_size	= sizeof(binary_limine_hdd_bin_data);
	U64 *limine_stage2	= limine + 0x1A4;
	CBlkDev				*bd = Letter2BlkDev(drv_let);
	CMasterBoot			 old_mbr, *new_mbr = limine;

	if (limine_size == 0)
	{
		"\n" ST_ERR_ST "Limine HDD MBR binary bytes not found. Must first #include it, then recompile this file.\n";
		return FALSE;
	}

	'\n';

	*limine_stage2 = 0x200;

	BlkDevLock(bd);

	AHCIAtaBlksRead(bd, &old_mbr, 0, 1); // read old MBR currently on disk
	MemCopy(new_mbr->p, old_mbr.p, sizeof(CMasterBoot.p)); // copy old MBR partition table to new Limine MBR

	// read the whole MBR + post-MBR-gap that Limine wants to overwrite, save all of that as an OldMBR.BIN
	BootMHDOldRead(drv_let, drv_let, 63);

	AHCIAtaBlksWrite(bd, limine, 0, 63); // write Limine to MBR and post-MBR gap

	BlkDevUnlock(bd);

	LimineCFGMake(drv_let);

	"\nLimine BSD2-licensed HDD MBR Boot Loader installed.\n\n";

	return TRUE;

}
