#define STD_DISTRO_DVD_CONFIG 	"TB\nScale2Mem(2048,0x40000)\nT\n\n\n\n"

U0 MakeMyISO()
{
	U8 *_out_iso_filename = "/Tmp/MyDistro.ISO.C";
	U8 *out_iso_filename = FileNameAbs(_out_iso_filename);
	U8 *start_os_after_system = "CHashFun *tmpf;\n"
			"if ((tmpf = HashFind(\"UsbBootInit\", Fs->hash_table, HTT_FUN)) &&\n"
			"\t\t!Bt(&tmpf->flags, Cf_EXTERN) && !Bt(&tmpf->flags, Ff__EXTERN))\n"
			"{\n"
			"\tExePrint(\"UsbBootInit;\");\n"
			"}\n";
	I64 line_count = LineRep("/*", "-r") + LineRep("/System/*") + LineRep("/Compiler/*", "-S+$$") + LineRep("/Kernel/*");

	if (!DriveIsWritable())
	{
		"Drive must be writable.	Install on Hard drive, first.\n";
		return;
	}

	DocTreeFWrite("/System/Define.ZC", "LineRep", "DefinePrint(\"DD_ZEALOS_LOC\",\"%,d\");\n", line_count);
	DefinePrint("DD_ZEALOS_LOC", "%,d", line_count);

	"Total LOC:%12,d\n\n", line_count;

	DelTree("/Distro");
	Del(out_iso_filename);

	ProgressBarsReset;
	progress1_max = 14;
	StrCopy(progress1_desc, "Copying files to /Distro");

	DirMake("/Distro");
	In(STD_DISTRO_DVD_CONFIG);
	BootDVDIns;
	progress1++;

	Copy("/*", "/Distro");
	progress1++;
	DirMake("/Distro" BOOT_DIR);
	Move(BOOT_DIR_DVD_KERNEL_ZXE, "/Distro" BOOT_DIR_KERNEL_ZXE);
	progress1++;
	CopyTree("/Home", 		"/Distro/Home");
	Del("/Distro/Home/.auto_iso_build");
	Del("/Distro/Home/AutoISOBuild.DD");
	Del("/Distro/Home/AutoISOStage0.DD");
	Del("/Distro/Home/AutoISOStage1.DD");
	Del("/Distro/Home/AutoISOStage2.DD");
	Del("/Distro/Home/AutoISOStage3.DD");
	Del("/Distro/Home/AutoISOStage4.DD");
	Del("/Distro/Home/AutoISOStage5.DD");
	FileWrite("/Distro/Home/StartOSAfterSystem.ZC", start_os_after_system, StrLen(start_os_after_system));
	progress1++;
	Del("/Distro/Home/Registry.ZC");
	CopyTree("/System", 	"/Distro/System");
	progress1++;
	CopyTree("/Apps", 		"/Distro/Apps");
	progress1++;
	CopyTree("/Compiler",	"/Distro/Compiler");
	progress1++;
	CopyTree("/Demo", 		"/Distro/Demo");
	progress1++;
	CopyTree("/Doc",		"/Distro/Doc");
	progress1++;
	CopyTree("/Kernel", 	"/Distro/Kernel");
	progress1++;
	CopyTree("/Misc", 		"/Distro/Misc");
	progress1++;

	CopyTree("/Downloads", "/Distro/Downloads");
	progress1++;
	DirMake("/Distro/Tmp");
	DirMake("/Distro/Tmp/ScreenShots");
	progress1++;
	StrCopy(progress1_desc, "Building ISO");
	RedSeaISO(out_iso_filename, "/Distro", "/Distro" BOOT_DIR_KERNEL_ZXE);
	progress1++;

	//If CD-ROM use MT_CD instead of MT_DVD.
	//DVDImageWrite('T',out_iso_filename,MT_DVD); //Uncomment to burn.

	Copy("/Distro" BOOT_DIR_KERNEL_ZXE, "/Tmp/DVD" KERNEL_ZXE);

	DelTree("/Distro");
	ProgressBarsReset;
	Free(out_iso_filename);
}
MakeMyISO;
Del("C:/Home/.auto_iso_build");
Del("C:/Home/AutoISOBuild.DD");
Del("C:/Home/AutoISOStage0.DD");
Del("C:/Home/AutoISOStage1.DD");
Del("C:/Home/AutoISOStage2.DD");
Del("C:/Home/AutoISOStage3.DD");
Del("C:/Home/AutoISOStage4.DD");
Del("C:/Home/AutoISOStage5.DD");
OutU8(0x501,0x31);
