U0 Auto()
{
	I64			 i, ata_port = -1;
	CAHCIPort	*port;
	U8			*in_str;

	for (i = 0; i < AHCI_MAX_PORTS; i++)

	{
		if (PCIBt(&blkdev.ahci_hba->ports_implemented, i))
		{
			port = &blkdev.ahci_hba->ports[i];
			if (port->signature == AHCI_PxSIG_ATA)
			{
				ata_port = i;
				break;
			}
		}
	}

	WinMax;
	BootMHDIns('C');
	Copy("C:/Tmp/OSBuild/Kernel/KStart16.ZC", "C:/Kernel/");
	Copy("C:/Tmp/OSBuild/Kernel/KernelA.HH", "C:/Kernel/");
	in_str = MStrPrint("CC\n%d\n\n\n\n\n\n", ata_port);
	Sleep(700);
	In(in_str);
	BootHDIns;
	Free(in_str);
	Del("C:/Home/AutoISOStage1.DD",, FALSE, FALSE);
	FileWrite("C:/Home/AutoISOStage2.DD", "2", 1);
	Reboot;
}
Auto;
